### ISSUE TITLE
how to use entity service ?

### ISSUE THREAD

**Issue by knodejs** [ctorx/ctorx.Core.Data#1]
public class YourEntityService : DbContextService<YourDbContext>, IYourEntityService
  {
    /// <summary>
    /// Sample method to fetch a list of entities
    /// </summary>
    public async Task<IList<YourEntity>> GetRecentAddedEntitiesAsync()
    {
      return await this.GetSet<YourEntity>()
        .Where(x => x.SomeProperty)
        .ToListAsync();
    }
  }

this.GetSet error when compile

**Comment by ctorx** [comment]
The library is a layer of functionality on top of Entity Framework, so in order for this to work you need a few other things setup such as a DbContext, entity lists, entities and startup dependencies.
